server:
  port: 3299
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jweb-eautoopen-gateway
  profiles:
    active: ${cfg.env}
  redis:
    timeout: 5000
    sentinel:
      master: iplatform-master
      nodes:
        - 10.1.109.97:26379
        - 10.1.109.97:26479
        - 10.1.109.98:26379
        - 10.1.109.98:26479
    pool:
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 10000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启基于注册中心的路由表。gateway可以通过开启以下配置来打开根据服务的serviceId来匹配路由
      default-filters:
      routes:    #路由配置：断言
        - id: open-platform
          uri: lb://JWEB-EAUTOOPEN    #uri: lb://JWEB-EAUTOOPEN  eurake路由ID  ； uri: http://localhost:3200  直接地址
          predicates:  # 路由规则，如失败则返回404
            - Path=/platform/open/**  #拦截条件
            - Method=GET    #限定请求类型
          filters:
            - PreserveHostHeader  #送原始host header
            - PrefixPath=/open/template    #将地址拼接到uri最前面
            - name: Hystrix    # 熔断降级配置
              args:
                name: fallback    #hystrixcommond会找到此name
                fallbackUri: forward:/normalfallback   # forward: 后面就是降级地址







#注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   # 在注册中心显示客户端 ip
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
#      defaultZone: http://localhost:1111/eureka/,http://127.0.0.1/eureka/    # 多地址方式

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    fallback:   #定制断路时间
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
    defualt:   #默认断路时间
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
  shareSecurityContext: true